
version: '2'
services:
    daspanel-load-balancer-caddy:
        build:
            context: .
            dockerfile: Dockerfile
        image: daspanel/load-balancer-caddy
        volumes:
            - ./data:/opt/daspanel/data
        networks:
            - frontend
            - backend
        env_file:
            - daspanel.env
networks:  
  frontend:
    driver: bridge
  backend:
    driver: bridge


