#!/usr/bin/with-contenv sh

# Installation UUID must be informed
if [ -z "$DASPANEL_SYS_UUID" ]; then
    echo "***"
    echo "ERROR: You must set the env variable DASPANEL_SYS_UUID to a valid UUID"
    echo "***"
    exit 1
fi

case "$DASPANEL_WAIT_FOR_API" in
    YES|yes|Yes)
        echo "[DASPANEL] Waiting 60 seconds for API: $0" >&2
        /opt/daspanel/bin/wait-for-api -t 60 $DASPANEL_SYS_APISERVER/info/status
        result=$?
        if [ ! $result -eq 0 ] ; then
            echo "[DASPANEL] Can not connect to API: $DASPANEL_SYS_APISERVER/info/status" >&2
            exit 1
        fi
        ;;
    *) 
        echo "[DASPANEL] Container not need to wait API become online: $0" >&2
        exit 1
        ;;
esac

# Get system configs from API server and set env variables
SYSCFG=$(wget -O- --header=Content-Type:application/json --header="Authorization: $DASPANEL_SYS_APIKEY" "$DASPANEL_SYS_APISERVER/tenants/$DASPANEL_SYS_UUID")
result=$?
if [ ! $result -eq 0 ] ; then
    echo "[DASPANEL] Unable to get tenant configuration from API server: $0" >&2
    exit 1
fi
export DASPANEL_SYS_HOSTNAME=`echo $SYSCFG | /usr/bin/jq -r '.sys.hostname'`
export ENGINE="load-balancer"

if [ ! -d "/etc/caddy" ]; then
    mkdir -p /etc/caddy
fi
if [ ! -d "/etc/caddy/sites-available" ]; then
    mkdir -p /etc/caddy/sites-available
fi
if [ ! -d "/etc/caddy/sites-enabled" ]; then
    mkdir -p /etc/caddy/sites-enabled
fi
if [ ! -d "/etc/caddy/certs" ]; then
    mkdir -p /etc/caddy/certs
fi

# Configure OpenSSL
if [ ! -d "/opt/daspanel/data/$DASPANEL_SYS_UUID/certs/self/ca" ]; then
	mkdir -p "/opt/daspanel/data/$DASPANEL_SYS_UUID/certs/self/ca"
fi
/usr/bin/gomplate -d cfg=$DASPANEL_SYS_APISERVER/tenants/$DASPANEL_SYS_UUID \
    -H "cfg=Authorization: $DASPANEL_SYS_APIKEY" \
    < /opt/daspanel/conf-templates/load-balancer/ssl/self-ca.cnf.tmpl \
    > /opt/daspanel/data/$DASPANEL_SYS_UUID/certs/self/ca/self-ca.cnf

# Configure Account CA
/opt/daspanel/bin/load-balancer/configure-rootca.sh $DASPANEL_SYS_UUID

# Create control panel certs
/opt/daspanel/bin/load-balancer/gen-cert.sh $DASPANEL_SYS_HOSTNAME

# Configure caddy
/usr/bin/gomplate -d cfg=$DASPANEL_SYS_APISERVER/tenants/$DASPANEL_SYS_UUID \
    -H "cfg=Authorization: $DASPANEL_SYS_APIKEY" \
    < /opt/daspanel/conf-templates/load-balancer/caddy/caddyfile.tmpl \
    > /etc/caddy/caddyfile

# Get sites http entries
/opt/daspanel/bin/load-balancer/daspanel.sites.sh

# secure daspanel
chown -R daspanel:daspanel /opt/daspanel/data
chown -R daspanel:daspanel /opt/daspanel/log

