#!/usr/bin/with-contenv sh

# Installation UUID must be informed
if [ -z "$DASPANEL_SYS_UUID" ]; then
    echo "***"
    echo "ERROR: You must set the env variable DASPANEL_SYS_UUID to a valid UUID"
    echo "***"
    exit 1
fi

if [ ! -d "/etc/caddy" ]; then
    mkdir -p /etc/caddy
fi
if [ ! -d "/etc/caddy/sites-available" ]; then
    mkdir -p /etc/caddy/sites-available
fi
if [ ! -d "/etc/caddy/sites-enabled" ]; then
    mkdir -p /etc/caddy/sites-enabled
fi

export DASPANEL_SYS_HOSTNAME=`cat /opt/daspanel/data/$DASPANEL_SYS_UUID/db/sysconfig.json | /usr/bin/jq -r '.sys.hostname'`
export DASPANEL_SYS_APISERVER=`cat /opt/daspanel/data/$DASPANEL_SYS_UUID/db/sysconfig.json | /usr/bin/jq -r '.sys.apiserver'`

# Configure caddy
/usr/bin/gomplate -d cfg=file:///opt/daspanel/data/$DASPANEL_SYS_UUID/db/sysconfig.json \
  < /opt/daspanel/conf-templates/load-balancer/caddy/caddyfile.tmpl \
  > /etc/caddy/caddyfile

# Get sites http entries
export DASPANEL_HTTP_ENGINE="load-balancer"
/usr/sbin/daspanel.sites.sh

# secure daspanel
chown -R daspanel:daspanel /opt/daspanel/data
chown -R daspanel:daspanel /opt/daspanel/log

