#!/usr/bin/with-contenv sh

# Installation UUID must be informed
if [ -z "$DASPANEL_SYS_UUID" ]; then
    echo "***"
    echo "ERROR: You must set the env variable DASPANEL_SYS_UUID to a valid UUID"
    echo "***"
    exit 1
fi

case "$DASPANEL_WAIT_FOR_API" in
    YES|yes|Yes)
        echo "[DASPANEL] Waiting 60 seconds for API: $0" >&2
        /opt/daspanel/bin/wait-for-api -t 60 $DASPANEL_SYS_APISERVER/info/status
        result=$?
        if [ ! $result -eq 0 ] ; then
            echo "[DASPANEL] Can not connect to API: $DASPANEL_SYS_APISERVER/info/status" >&2
            exit 1
        fi
        ;;
    *) 
        echo "[DASPANEL] Container not need to wait API become online: $0" >&2
        exit 1
        ;;
esac

# Get system configs from API server and set env variables
SYSCFG=$(wget -O- --header=Content-Type:application/json --header="Authorization: $DASPANEL_SYS_APIKEY" "$DASPANEL_SYS_APISERVER/tenants/$DASPANEL_SYS_UUID")
result=$?
if [ ! $result -eq 0 ] ; then
    echo "[DASPANEL] Unable to get tenant configuration from API server: $0" >&2
    exit 1
fi
export DASPANEL_SYS_HOSTNAME=`echo $SYSCFG | /usr/bin/jq -r '.sys.hostname'`
export ENGINE="load-balancer"

DASPANEL_REDIS_SERVER=`echo $SYSCFG | /usr/bin/jq -r '.redis.server'`
DASPANEL_REDIS_PORT=`echo $SYSCFG | /usr/bin/jq -r '.redis.port'`
DASPANEL_REDIS_DATABASE=`echo $SYSCFG | /usr/bin/jq -r '.redis.database'`
DASPANEL_REDIS_SERVER=`echo $SYSCFG | /usr/bin/jq -r '.redis.server'`
DASPANEL_REDIS_USER=`echo $SYSCFG | /usr/bin/jq -r '.redis.user'`
DASPANEL_REDIS_PASSWORD=`echo $SYSCFG | /usr/bin/jq -r '.redis.password'`

PUBSUB_SERVER="$DASPANEL_REDIS_SERVER:$DASPANEL_REDIS_PORT:$DASPANEL_REDIS_DATABASE:$DASPANEL_REDIS_PASSWORD"
exec /usr/sbin/redis-exec $PUBSUB_SERVER $DASPANEL_SYS_UUID:daspanel:sites /opt/daspanel/bin/load-balancer/daspanel.sites.sh


